### ISSUE TITLE
Ingest handler never returns errors to Vercel

### ISSUE THREAD

**Issue by miceg** [dacbd/vercel-log-drain#8]
It appears that the Ingest handler always returns HTTP 200 OK, even when there are errors:

https://github.com/dacbd/vercel-log-drain/blob/fafe68bd3c6c4af076cb7dfce41e1407c563d650/src/main.rs#L173-L186

This means that [Vercel cannot notify when there is an issue with the log drain](https://vercel.com/docs/observability/log-drains#errored-log-drains).

**Comment by dacbd** [comment]
Yes that is correct, that is how I originally implemented it (to always
respond 200), to prevent any kind of probing.

We can change this to a 422 status code if the signature validation fails.
Is that a change that you would like to see?

**Comment by dacbd** [comment]
@miceg I've made a few improvements adding a few more response codes, which you can checkout in main or try the latest release for your project.

Let me know if this isn't what you had in mind.

for completeness, the codes are:
- `400` if there is no signature
- `406` if the body is invalid utf-8
- `422` if the signature is invalid
- `200` for other cases

**Comment by miceg** [comment]
That's what I had in mind. Thank you for your prompt response!

The only things I'd suggest are:

* ~~"No signature" and "bad signature" should both return `403`, and the same headers for both – is it possible to drop the `x-vercel-verify` header there?~~

  ~~That would make the handler more resistant to probing, aside from timing attacks.~~

  **Edit:** this breaks things: https://github.com/dacbd/vercel-log-drain/issues/8#issuecomment-2325641416

* The ingestion handler should only try to decode UTF-8 or do other processing *after* the body's signature has been verified.

* It looks like if the message now sent to a background queue, but if any entry returns an error, it still returns HTTP 200 OK.

  Is it possible to submit and validate these atomically?

**Comment by miceg** [comment]
I've now actually deployed this, and I've noticed that my suggestion breaks on Vercel's verification process... sorry about that! :(

Vercel **does not** set an `x-vercel-signature` header for this verification process, even if you've set up a custom secret in the Vercel panel:

```json
{
    "host": REDACTED,
    "content-length": "2",
    "content-type": "text/plain;charset=UTF-8",
    "accept": "*/*",
    "user-agent": "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)",
    "accept-encoding": "gzip,deflate"
}
```

To fix this, I updated `handlers::injest()` with:

```rust
    let signature = match headers.get("x-vercel-signature") {
        Some(signature) => signature.to_str().unwrap(),
        None => {
            warn!(?headers, "received payload without signature");
            counter!("drain_recv_invalid_signature").increment(1);
            // Vercel's verificaion request doesn't actually sign the request,
            // even if you set a custom secret in advance.
            return Response::builder()
                .status(StatusCode::OK)
                .header("x-vercel-verify", state.vercel_verify)
                .body(Body::empty())
                .expect("Defined Responses to be infalliable.");
        }
    };
```

*Thankfully,* it looks like custom static headers set during the setup process *are* used by the verification process.

I've ended up putting in an extra rule in the load balancer to check a static request header, and drop everything that doesn't matter. That at least means that > 99% of bot traffic gets dropped without touching `vercel-log-drain`.

**Comment by dacbd** [comment]
Are you willing to contribute to the README with some of these notes? I'll
get your PR merged soon, as well and a few more tweaks.

**Comment by miceg** [comment]
Yeah, that's fine. I actually have a small queue of tweaks and fixes to upstream. 😄 

I've also opened a support ticket open with Vercel, I feel like that missing header is a bug on their side.

**Comment by dacbd** [comment]
Awesome, thanks.

I should get your first PR merged in the next 8 hrs or so. I need to double
check their documentation but I believe the JSON scheme they send In the
verification is also inconsistent with what the docs say the expected
payload is.

Did you notice that when you verified yours? Any payloads fail to parse? I
need to setup a new project to test with but I am away for a bit.

**Comment by miceg** [comment]
Yup, I noticed it was inconistent. The test data Vercel sent was (literally):

```json
[
  {
    "id": "1669188782687374643267100000",
    "message": "SAMPLE MESSAGE: Inside middleware hello",
    "timestamp": 1725343693334,
    "type": "stdout",
    "requestId": "xxxxx-xxxxxxxxxxxxx-xxxxxxxxxxxx",
    "projectId": "prj_xxxxxxxxxxxxxxxxxxxxxx",
    "deploymentId": "dpl_xxxxxxxxxxxxxxxxxxxxxx",
    "source": "edge",
    "host": "my-app.vercel.sh",
    "path": "/api/hello"
  },
  {
    "id": "1669188782687374643267100001",
    "message": "SAMPLE MESSAGE: Inside middleware 2",
    "timestamp": 1725343693334,
    "type": "stdout",
    "requestId": "xxxxx-xxxxxxxxxxxxx-xxxxxxxxxxxx",
    "projectId": "prj_xxxxxxxxxxxxxxxxxxxxxx",
    "deploymentId": "dpl_xxxxxxxxxxxxxxxxxxxxxx",
    "source": "edge",
    "host": "my-app.vercel.sh",
    "path": "/api/hello"
  }
]
```

I ended up copying that into a new test fixture and checking it in `app::tests::ingest_test_samples`:

```diff
--- a/src/app.rs
+++ b/src/app.rs
@@ -65,12 +67,14 @@ mod tests {
     }
     #[tokio::test]
     async fn ingest_check_samples() -> Result<()> {
+        let _ = tracing_subscriber::fmt().json().try_init();
         let test_data = vec![
             include_str!("fixtures/sample_1.json"),
             include_str!("fixtures/sample_2.json"),
             include_str!("fixtures/sample_3.json"),
             include_str!("fixtures/sample_4.json"),
             include_str!("fixtures/sample_5.json"),
+            include_str!("fixtures/sample_6.json"),
         ];

         let (tx, rx) = tokio::sync::mpsc::unbounded_channel::<types::Message>();
@@ -107,11 +111,12 @@ mod tests {
             );
             assert_eq!(response.status(), StatusCode::OK);
         }
-        assert_eq!(rx.len(), 8);
+        assert_eq!(rx.len(), 10);
         return Ok(());
     }
```

Once I made `Message::project_name` an `Option<String>` (rather than `String`), it seems to deserialise correctly.

I needed to tweak the Cloudwatch driver to handle that too:

```diff
--- a/src/drivers/cloudwatch.rs
+++ b/src/drivers/cloudwatch.rs
@@ -176,7 +176,11 @@ impl LogDriver for CloudWatchDriver {

     async fn send_log(&mut self, message: &Message) -> Result<()> {
         let mut retries: usize = 0;
-        let group_name = format!("/vercel/{}/{}", message.project_name, message.source);
+        let project_name = match &message.project_name {
+            Some(n) => n.as_str(),
+            None => "null",
+        };
+        let group_name = format!("/vercel/{project_name}/{}", message.source);
         #[allow(clippy::useless_format)]
         let stream_name = format!("{}", message.deployment_id);
         self.check_or_create(&group_name, &stream_name).await?;
```

And now I can see those test logs in Cloudwatch:

<img width="1123" alt="Screenshot 2024-09-03 at 16 59 35" src="https://github.com/user-attachments/assets/8b43b732-ed40-4445-9930-c1cb836041aa">

I'm planning to make a proper PR for this stuff, I've spent most of today troubleshooting Terraform and IAM policies. 😫

**Comment by dacbd** [comment]
Awe, thanks, I thought I had properly listed the minimum required iam
permissions in the readme with a terraform example but I might be mistaken.

**Comment by miceg** [comment]
> Awe, thanks, I thought I had properly listed the minimum required iam permissions in the readme with a terraform example but I might be mistaken.

What you had was helpful to get started. I made the policies slightly stricter policies so that it could only write to log groups in `/vercel/*`, and I also had to write policies for our CI/CD infrastructure. 😄 

My version of the policies currently has some duplication. It will take a little bit of trial and error on my part to get fixed that up.

**Comment by dacbd** [comment]
When you mentioned debugging a policy I figured something like that was probably the case. I thought about making the prefix something that can be configured, `/{user-defined}/*` or `/{user-defined}/vercel/*`

**Comment by miceg** [comment]
I've now finished fixing that stricter policy. What I ended up with was:

```terraform
data "aws_caller_identity" "current" {}

data "aws_iam_policy_document" "vercel_log_drain_task_policy" {
  statement {
    actions = [
      "logs:CreateLogGroup",
      "logs:PutRetentionPolicy",
    ]
    resources = [
      provider::aws::arn_build(
        "aws",
        "logs",
        var.aws_region,
        data.aws_caller_identity.current.account_id,
        "log-group:/vercel/*"
      )
    ]
  }

  statement {
    actions = [
      "logs:CreateLogStream",
      "logs:DescribeLogStreams",
      "logs:PutLogEvents",
    ]
    resources = [
      provider::aws::arn_build(
        "aws",
        "logs",
        var.aws_region,
        data.aws_caller_identity.current.account_id,
        "log-group:/vercel/*:*"
      )
    ]
  }

  statement {
    actions = [
      "logs:DescribeLogGroups",
    ]
    resources = ["*"]
  }
}
```

While I can see value in letting you customise the prefix (eg: if you're running multiple instances in the same AWS account), what's there now works well enough.

The AWS account I'm running it in is exclusively used by one instance of `vercel-log-drain`, which monitors one Vercel team (with multiple sites). I've got [an AWS Organisation account](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_introduction.html) set up, so spinning up more AWS accounts is easy enough should the need arise.

**Comment by dacbd** [comment]
Great, I think I have one or two more changes I will push soon. If there are any other problems let me know.

Also happy to take any more PRs you might want to send. I would love it if you gave the repo a star, it helps my fragile ego 😆
